---
title: 'Homework Assignment #8'
output: html_document
---

## Problem 1

A.  Load [Howell's craniometric dataset](http://hompal-stats.wabarr.com/datasets/Howell_craniometry.txt)
B.  Get rid of unwanted data. Select only the following columns: <span style="color:red;">ID, Sex, Population, BNL, MDH, EKB, ZOR, BAA, NBA</span>. Filter the dataset to only include individuals from the following populations: <span style="color:red;">BUSHMAN, PERU, NORSE, ZULU</span>.
C.  Use the `pairs()` function on just the 6 numeric variables (exclude the ID variable) in order to get a visual feel for the covariance among the variables. 
F.  Calculate the variance / covariance matrix for the 6 numeric variables.

## Problem 2

A.  Compute a Euclidian distance matrix for the 6 numerical variables.  **Save this to a variable, DO NOT PRINT THIS TO THE SCREEN OR INCLUDE IT IN THE OUTPUT**
B.  Perform a hierarchical cluster analysis using the distance matrix you just computed. Use the `hclust()` function for this
C.  Plot the cluster analysis dendrogram. 

## Problem 3

A.  Perform a discriminant function analysis to see how well the 6 numeric variables predict the Population. Use the `lda()` function in the MASS package. 
B.  Which of the six variables is the most important for discriminating between populations? Justify your answer.
C.  Use the `predict()` function to predict how each of the datapoints would be classified by your discriminant function analysis. Save the predictions in a variable called `predictions`.  Explore the list of predictions (there is a lot of useful stuff in there!!!)
D.  Extract the predicted population (in the `class` portion of the `predictions` object).  Calculate the proportion of these predictions that are the same as their known population. 
E.  Look at the `x` portion of the `predictions` object.  This contains the actual canonical discriminant scores for each individual.  Make a scatter plot of the first and second discriminant functions.  Color code the points by the actual population (not the predicted population, which may be different).
F.  Was this DFA successful in discriminating groups?  Why or why not?  Explain your answer. 