---
title: 'Homework # 10'
output: html_document
---

## Problem #1

A.  Read in the [morphometric data from Barr, 2014](http://hompal-stats.wabarr.com/datasets/barr_astrag_2014.txt) on bovid astragali. 

B. Select the following colums from the data: `Taxon`, `B`, `DistRad`, and `Habitat`.  Create a new dataframe with the `Taxon`, the `Habitat` and  species means for `B` and `DistRad`.

C.  Read in [the ruminant phylogeny from Hernández Fernández & Vrba, 2007](http://hompal-stats.wabarr.com/datasets/ruminants.phy). 


D.  Combine the data and the tree using `comparative.data()` to ready the tree for pgls.  ***Note: if you used `dplyr` in the steps above, you need to change the class of the resulting dataframe, because there is a bug in `caper` and it won't deal with a `dplyr` `tbl_df` object.  You can use this line of code to fix it `class(dataframeFromDplyr) <- "data.frame"`***

E. Plot the trimmed tree that includes just the taxa of interest in the astragalus dataset. Make it as beautiful as you can. 


F.  Perform PGLS to test the hypothesis that `log(B)` is a function of `log(DistRad)`, while controling for phylogenetic signal.

G. Plot `log(B)` as a function of  `log(DistRad)`, and color code the points by habitat type.
