---
title: "Homework #5"
output: html_document
---

## Problem 1

Use the data set of measurements of antelope astragali from [Barr (2014)](datasets/barr_astrag_2014.txt). 

A.  Read in the data, saving it to a variable called `astrag`.
B.  Make a scatterplot with the natural logarithm of measurement `B` on the x-axis and the natural logarithm of measurement `DistRad` on the y-axis.
C.  Calculate the ordinary least-squares (OLS) regression for DistRad as a function of B, and print a `summary()` of this data.
D.  Calculate the reduced major axis regression (RMA) for the same variables. **Note** the `lmodel2` package uses "RMA"" to refer to "Ranged Major Axis", which is different.  You want what `lmodel2` calls Standardized Major Axis (SMA), which is equivalent to what we call reduced major axis (RMA) in our literature. 
E.  Is the OLS slope greater or less than the RMA slope?
F.  Add both the OLS and the RMA regression lines to the plot created in 1B.  Make sure the two lines have different colors and/or line types, and that they are labeled so I know which is which. 
G.  use the `plot()` function to plot regression diagnostic plots for the OLS regression. Do the assumptions of linear regression appear to be met? Explain your answer.
H.  Extract the residuals from the OLS regression, and make a histogram of them, with the appropriate labels and title for the plot.
I.  Calculate the species means for both variables, and add the species means as a new layer on your scatterplot.

