---
title: "Homework # 6"
---

## Problem # 1

Using this fake dataset on [lemur feeding rates](http://hompal-stats.wabarr.com/datasets/lemurfeeding.txt) do a two-factor ANOVA to determine whether feeding rate is influenced by sex and by the group each individual belongs to. 

A.  Make a boxplot of feeding rate by sex
B.  Make a boxplot of feeding rate by group
C.  Show the ANOVA table for the two way ANOVA
D.  Explore the interaction between the two factors by creating a plot analogous to figure 10.3 (p 329) in the Gotelli book. Put the group on the X axis, and the mean feeding rate for each group on the Y axis (make this a line going across all factor levels). Color code the lines by sex. *Do not use the `interaction.plot()` shortcut to make this plot.* 
E. Explain whether or not there is an interaction between the two factors.  

## Problem # 2

Write a function to simulate ANOVA type data, with two groups and some difference in means between the groups. You can simulate the data using the equation you saw in the ANOVA slide show. 

$$Y_{ij}=\mu + A_i + \epsilon_{ij}$$

Assume that the design is balanced (groups have same sample size). 

Your function should take the following arguments and default values:

* `sampleSize` default 20. The total sample size of both groups combined
* `grandMean` default 50. The grand mean of the data (ignoring group)
* `errorSD` default 5. The standard deviation of the error term
* `meanDiff` default 3. The difference between the means of the two treatment groups

Your function should do the following:

* create the error term
* create the grouping vector
* simulate the y variable using the supplied parameters
* make a boxplot with the groups on the x axis and the value of y on the y axis (you may have to explicitly `print` your plot if you use ggplot2 from within your function)
* do the ANOVA
* return the p value from the anova

### Play around with your function, and systematically change the parameters to get a feel for how the parameters change the p-value. 

### End by answering the following questions:

A.  what effect (if any) does increasing the sample size have on the p value for a given set of parameters?
B.  what about increasing the grand mean?
C.  what about increasing the standard deviation of the error term

***make sure to show me a run of your function to prove that it works!**


