---
title: "Demos, Readings, & Homework" 
---

## Due at beginning of class on the day listed. 


Date  | Demo | Homework  | Reading | Student Presentation 
------ | ---------  | --------- | -------- | ------- 
Jan 12 | [Intro to R](intro_to_R.html) | [Try R Tutorial](http://tryr.codeschool.com) | - | - 
Jan 19 | **MLK Day, No Class** | - | - | - 
Jan 26 | [Visualizing Data](visualization.html) & [Automation](automation.html) | [HW #1](homework_assignment_1.html) - [Solution](homework_solutions/HW_1_solution.html) | [dplyr vignette](http://cran.rstudio.com/web/packages/dplyr/vignettes/introduction.html) | - 
Feb 2	|  [Probability](probability.html) - [Distributions](distributions.html) - [Summary Stats](summary_stats.html) | [HW #2](homework_assignment_2.html) - [Solution](homework_solutions/HW_2_solution.html) | Gotelli: Ch 1 - 3 | -
Feb 9 | [Hypothesis Testing](hypothesis_testing.html) | [HW #3](homework_assignment_3.html) - [Solution](homework_solutions/HW_3_solution.html)  | [Blog post](https://oikosjournal.wordpress.com/2011/10/11/frequentist-vs-bayesian-statistics-resources-to-help-you-choose/); Gotelli: Ch 4 - 5 | -
Feb 16 | **President's Day, No Class** | [Optional R Exercise](R_Skills_Practice.html)  | - | - 
Feb 23 | [Correlation and Regression](regression.html) | [HW #4](homework_assignment_4.html) - [Solution](homework_solutions/HW_4_solution.html)  | Gotelli: Ch 9 - [Gordon et al., 2008](readings_pdf/PNAS-2008-Gordon et al.-LB1-Scaling.pdf) | [Clare Kimock](studentdemos/clare_kimok_regression.html)
Mar 2 | **Exam I** | - | - | - 
Mar 9 | **Spring Break, No Class** | - | - | - 
Mar 16 | [Tidy Data](tidyR.html) & [ANOVA and ANCOVA](ANOVA.html) | [HW #5](homework_assignment_5.html) - [Solution](homework_solutions/HW_5_solution.html)   | Gotelli: Ch 10, [Cerling et al. 2013](readings_pdf/Cerling_etal_2013.pdf), [Boddy et al., 2012](readings_pdf/Boddy_etal_2012.pdf) | [Eve Boyle](studentdemos/Boyle_Cerling_ANOVA.html) & [Lawrence Fatica](studentdemos/Fatica_ANCOVA_Presentation.html)
Mar 23 | [Power](power_analysis.html) & [Categorical Data](categorical_data.html) | [HW #6](homework_assignment_6.html) - [Solution](homework_solutions/HW_6_solution.html)  | Gotelli: Ch 11, [Cuozo et al, 2013](readings_pdf/Cuozo_etal_2013.pdf), [Scorrano, 2014](readings_pdf/Scorrano_2014_palaeodiet.pdf)| [Megan Vakiener](studentdemos/Vakiener.html) & [Emily Brennan](studentdemos/Brennan.html)
Mar 30 | [Multivariate Stats: I](Multivariate_I.html) |  [HW #7](homework_assignment_7.html) - [Solution](homework_solutions/HW_7_solution.html) | Manly Ch. 1 - 5, [Zaatari et al](readings_pdf/Zaatari_etal_2011.pdf), [Espinoza et al, 2007](readings_pdf/Espinoza_etal_2007.pdf)| [Robert Kaplan](studentdemos/Kaplan_DFA.html) & [Jon Reeves](studentdemos/JR_Cluster_Analysis.html)
Apr 6	| [String Formatting and Filesystem](String_Formatting_Filesystem.html) & [Multivariate Stats: II](Multivariate_II.html) |   [HW #8](homework_assignment_8.html) - [Solution](homework_solutions/HW_8_solution.html)| Manly Ch. 6 - 12, [Su et al., 2011](readings_pdf/Su_etal_2011.pdf), [Granatosky et al., 2014](readings_pdf/Granatosky_etal_2014.pdf) | [Kelly Ostrofsky](studentdemos/Ostrofsky_PCA.html) & [Enque Negash](studentdemos/Negash_Correspondence.html)
Apr 13 | [workflow](workflow.html) & [Multivariate Stats: III](Multivariate_III.html) |  [HW #9](homework_assignment_9.html) - [Submission Link](https://blackboard.gwu.edu/webapps/assignment/uploadAssignment?content_id=_6463832_1&course_id=_250829_1&assign_group_id=&mode=cpview) | [Anderson et al., 2011](readings_pdf/Anderson_etal_2011.pdf) | [Laurence Dumouchel](studentdemos/NMDS-Dumouchel.html)
Apr 20 | [Accounting for Phylogenetic Signal (PGLS)] |  [HW #10](homework_assignment_10.html) | - | Brian Schilder
Apr 27 | [Mixed-Models] |  [HW #11]() | [Crawley Ch. 10](readings_pdf/Crawley_Ch10_MixedEffects.pdf) | Sean Lee
Apr 29 |  **Exam II** (Note: this is designated Wednesday) | - | - | - 
