---
title: "Homework 8 Solution"
output: html_document
---

## 13 pts total

## Problem 1

### A - 1pt

```{r}
howell <- read.table("http://hompal-stats.wabarr.com/datasets/Howell_craniometry.txt", header=TRUE, sep=",")
library(dplyr)
```

### B - 1pt

```{r}
howell <- howell %>% 
  dplyr::select(ID, Sex, Population, BNL, MDH, EKB, ZOR, BAA, NBA) %>%
  dplyr::filter(Population %in% c("BUSHMAN", "PERU", "NORSE", "ZULU"))
head(howell)
```

### C - 1pt
```{r fig.width=12, fig.height=12}
pairs(howell[,4:9])
```

### D
### 1pt
```{r}
cov(howell[,4:9])
#gives the same results
var(howell[,4:9])
```

## Problem 2

### A - 1pt

```{r cache=TRUE}
distMat <- dist(x = howell[,4:9], method = "euclid")
```

### B - 1pt

```{r cache=TRUE}
HowellClust <- hclust(d = distMat, method = "average")
```

### C - 1pt

```{r fig.width=12, fig.height=12, cache=TRUE}
plot(HowellClust)
```

## Problem 3

### A - 1pt

```{r cache=TRUE}
detach("package:dplyr", unload=TRUE)
library(MASS)
howellDFA <- lda(Population ~ BNL + MDH + EKB + ZOR + BAA + NBA, data=howell)
howellDFA
```

### B - 1pt

The coefficient of the BAA variable has the greatest magnitude for LD1, so this is the most important variable for population discrimination. Note that the sign is negative....it is the absolute value that matters!

### C - 1pt

```{r cache=TRUE}
predictions <- predict(howellDFA, newdata = howell[,4:9])
sum(predictions$class == howell$Population) / nrow(howell)
```

### D - 1pt

```{r fig.height=12, fig.width=12}
library(ggplot2)
qplot(x=LD1, y=LD2, color = howell$Population, data=as.data.frame(predictions$x), size=I(5)) + theme_bw(30)
```

### E - 1pt

```{r}
sum(predictions$class == howell$Population) / length(predictions$class)
```


### F - 1pt

Answers may vary, but you must justify your answer.


